name: train1
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/WhatsApp Image 2020-05-23 at 9.57.30 PM.jpeg
   - images/WhatsApp Image 2020-05-23 at 9.57.31 PM.jpeg

